vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set relativenumber")
vim.cmd("set number")
vim.cmd("set mouse=r")
vim.cmd("set smartindent")
vim.cmd("set smarttab")
vim.cmd("set title")
vim.cmd("set wildmenu")
vim.cmd("set cursorline")
vim.g.mapleader = " "
